# This workflow will rebuild task stub directory when changes happen in the docs/tasks rst files
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Rebuild Task Stubs

on:
  push:
    branches: [ master ]
    paths: 
    - "docs/tasks/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install requests
    - name: Run script
      run: python ./scripts/parse_tasks.py
    - name: commit changed files
      run: git commit -m "auto task regen"
    - name: push code to master
      run: git push origin HEAD:master
  
